### ISSUE TITLE
标签里 163 key(Don't modify) 不如去掉^^

### ISSUE THREAD

**Issue by aoooookx** [lissettecarlr/ncmdump#4]
.mp3和.flac的对应标签位置![Snipaste_2024-06-24_08-04-28](https://github.com/lissettecarlr/ncmdump/assets/115018542/160df0e7-bb0f-4d69-83a9-094b1c6d30dd)
![Snipaste_2024-06-24_08-07-06](https://github.com/lissettecarlr/ncmdump/assets/115018542/c0993b6f-4d92-45c2-8238-ced6bab271ea)

**Comment by lissettecarlr** [comment]
客户端v0.3版本，移除了163 key。 
![1](https://github.com/lissettecarlr/ncmdump/assets/16299917/aa93fa6c-8a06-4cfa-a138-af76f7df992f)
