### ISSUE TITLE
拖入文件后没有反应

### ISSUE THREAD

**Issue by qpeuxb** [lissettecarlr/ncmdump#5]
拖入ncm文件后没有反应，上面写着Expecting 后面的被挡住了

**Comment by lissettecarlr** [comment]
刚在Windows 11中下载v0.3版本试了试，是可以的，我不确定是音频问题还是系统问题。可以的话，你把音频名字和系统告诉我，我再试试

**Comment by qpeuxb** [comment]
> 刚在Windows 11中下载v0.3版本试了试，是可以的，我不确定是音频问题还是系统问题。可以的话，你把音频名字和系统告诉我，我再试试

Windows 10 22H2，是我下载的一个播客内容，余华的《第七天》，不是歌曲，我试了试歌曲是可以的

**Comment by lissettecarlr** [comment]
我这边下载了几个版本的，发现都是mp3的格式，没能找到ncm的。
